// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "API文档仅用于Hello Peer研发使用。",
        "contact": {
            "name": "Frank Sheng",
            "email": "726569998@qq.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/authlogin": {
            "post": {
                "description": "通过传递微信登录code以及getUserProfile返回字段换取用户token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "授权用户登录",
                "operationId": "authlogin",
                "parameters": [
                    {
                        "description": "微信登录code以及getUserProfile返回字段",
                        "name": "code",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserProfileForm"
                        }
                    }
                ],
                "responses": {
                    "0": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/models.Token"
                        }
                    }
                }
            }
        },
        "/auth/autologin": {
            "post": {
                "description": "通过传递微信登录code换取用户token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "未授权用户登录",
                "operationId": "autologin",
                "parameters": [
                    {
                        "description": "微信登录code",
                        "name": "code",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AutoLogin"
                        }
                    }
                ],
                "responses": {
                    "0": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/models.Token"
                        }
                    }
                }
            }
        },
        "/images/{file_name}": {
            "get": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "获取图片",
                "tags": [
                    "Util"
                ],
                "summary": "获取图片",
                "operationId": "get_image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "0": {
                        "description": ""
                    }
                }
            }
        },
        "/settings/getRecommendSetting": {
            "get": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "可通过用户ID获取用户推荐设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Settings"
                ],
                "summary": "获取用户推荐设置",
                "operationId": "get_recommend_settings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "0": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/models.RecommendSetting"
                        }
                    }
                }
            }
        },
        "/settings/getSquareSetting": {
            "get": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "可通过用户ID获取用户广场设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Settings"
                ],
                "summary": "获取用户广场设置",
                "operationId": "get_square_settings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "0": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/models.SquareSettings"
                        }
                    }
                }
            }
        },
        "/settings/setRecommendSetting": {
            "post": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "可设置用户广场设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Settings"
                ],
                "summary": "设置用户广场设置",
                "operationId": "set_recommend_settings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "设置",
                        "name": "settings",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RecommendSetting"
                        }
                    }
                ],
                "responses": {
                    "0": {
                        "description": ""
                    }
                }
            }
        },
        "/settings/setSquareSetting": {
            "post": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "可设置用户广场设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Settings"
                ],
                "summary": "设置用户广场设置",
                "operationId": "set_square_settings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "设置",
                        "name": "settings",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SquareSettings"
                        }
                    }
                ],
                "responses": {
                    "0": {
                        "description": ""
                    }
                }
            }
        },
        "/user/deleteUserImage": {
            "post": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "删除用户图片",
                "tags": [
                    "User"
                ],
                "summary": "删除用户图片",
                "operationId": "delete_user_image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文件名",
                        "name": "filename",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "0": {
                        "description": ""
                    }
                }
            }
        },
        "/user/getRandomUserDetails": {
            "get": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "可通过用户ID获取用户详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "获取广场用户详情",
                "operationId": "get_random_users_details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "uid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "0": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/controllers.UserDetails"
                        }
                    }
                }
            }
        },
        "/user/getRandomUsers": {
            "post": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "可通过用户ID以及用户广场设置项获取随机用户列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "获取用户广场随机用户列表",
                "operationId": "get_random_users_list_in_square",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "分页",
                        "name": "pagination",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Pagination"
                        }
                    }
                ],
                "responses": {
                    "0": {
                        "description": "",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.RandomUser"
                            }
                        }
                    }
                }
            }
        },
        "/user/getRecommendedUsers": {
            "get": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "可通过用户ID获取推荐用户列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "获取用户推荐用户列表",
                "operationId": "get_recommended_users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "0": {
                        "description": "",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.RecommendedUser"
                            }
                        }
                    }
                }
            }
        },
        "/user/getUserDetails": {
            "get": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "可根据用户ID获取用户详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "根据用户ID获取用户详情",
                "operationId": "get_user_details_by_id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "user_id",
                        "name": "uid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "0": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/controllers.UserDetails"
                        }
                    }
                }
            }
        },
        "/user/getUserHomepageInfo": {
            "get": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "可获取用户首页信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "获取用户首页信息",
                "operationId": "get_user_homepage_info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "0": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/models.HomepageInfo"
                        }
                    }
                }
            }
        },
        "/user/getUserInfoCompleteLevel": {
            "get": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "可根据用户ID获取用户信息完成度 0-未完成 1-基本信息 2-基本信息+头像",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "根据用户ID获取用户信息完成度",
                "operationId": "get_user_info_complete_level",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "0": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/models.InfoCompletionLevel"
                        }
                    }
                }
            }
        },
        "/user/pet/deletePetImage": {
            "post": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "删除宠物图片",
                "tags": [
                    "Pet"
                ],
                "summary": "删除宠物图片",
                "operationId": "delete_pet_image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文件名",
                        "name": "filename",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "0": {
                        "description": ""
                    }
                }
            }
        },
        "/user/pet/getPetDetails": {
            "get": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "可获取宠物详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pet"
                ],
                "summary": "获取宠物详情",
                "operationId": "get_pet_details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "0": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/models.PetResponse"
                        }
                    }
                }
            }
        },
        "/user/pet/getPetDetailsById": {
            "get": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "可根据用户id获取宠物详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pet"
                ],
                "summary": "根据用户id获取宠物详情",
                "operationId": "get_pet_details_by_id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "uid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "0": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/models.PetResponse"
                        }
                    }
                }
            }
        },
        "/user/pet/initPet": {
            "post": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "用户可初始化宠物",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pet"
                ],
                "summary": "初始化宠物",
                "operationId": "init_pet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "0": {
                        "description": ""
                    }
                }
            }
        },
        "/user/pet/setPetDetails": {
            "post": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "用户可设置宠物详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pet"
                ],
                "summary": "设置宠物详情",
                "operationId": "set_pet_details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "宠物详情",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PetRequest"
                        }
                    }
                ],
                "responses": {
                    "0": {
                        "description": ""
                    }
                }
            }
        },
        "/user/pet/upload/setPetImage": {
            "post": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "用户可上传宠物图片",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pet"
                ],
                "summary": "设置宠物图片",
                "operationId": "set_pet_image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "宠物图片",
                        "name": "content",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "0": {
                        "description": ""
                    }
                }
            }
        },
        "/user/relation/getFans": {
            "get": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "可获取用户关注的人的列表。 status说明， 0 - 已关注， 1 - 已互关",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Relation"
                ],
                "summary": "获取用户关注的人的列表",
                "operationId": "get_fans_to_others",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "0": {
                        "description": "",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Fan"
                            }
                        }
                    }
                }
            }
        },
        "/user/relation/setFocusOn": {
            "post": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "可根据用户ID，目标用户ID，关注状态设置用户之间的关注。 0 - 取消关注， 1 - 新关注， 2 - 已关注（用户已阅）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Relation"
                ],
                "summary": "设置两个用户之间的关注",
                "operationId": "set_focus_on",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "0": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/models.FocusRequest"
                        }
                    }
                }
            }
        },
        "/user/setUserBasicInfo": {
            "post": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "可通过用户token设置用户基础信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "设置用户基础信息",
                "operationId": "set_user_basic_info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户基础信息",
                        "name": "basicInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BasicInfo"
                        }
                    }
                ],
                "responses": {
                    "0": {
                        "description": ""
                    }
                }
            }
        },
        "/user/setUserDetails": {
            "post": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "用户可设置信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "设置用户信息",
                "operationId": "set_user_details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UserDetailsUpdate"
                        }
                    }
                ],
                "responses": {
                    "0": {
                        "description": ""
                    }
                }
            }
        },
        "/user/setUserGender": {
            "post": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "可通过用户token设置用户性别",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "设置用户性别",
                "operationId": "set_user_gender",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "用户性别",
                        "name": "gender",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserGender"
                        }
                    }
                ],
                "responses": {
                    "0": {
                        "description": ""
                    }
                }
            }
        },
        "/user/tencent/getUserIMSig": {
            "get": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "可获取用户腾讯IM签名",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tencent"
                ],
                "summary": "获取用户腾讯IM签名",
                "operationId": "get_user_im_sig",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserIMSig"
                        }
                    }
                }
            }
        },
        "/user/upload/setUserAvatar": {
            "post": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "用户可设置头像",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "设置用户头像",
                "operationId": "set_user_avatar",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "头像文件",
                        "name": "content",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "0": {
                        "description": ""
                    }
                }
            }
        },
        "/user/upload/setUserCover": {
            "post": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "用户可设置封面图",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "设置用户封面图",
                "operationId": "set_user_cover",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "封面文件",
                        "name": "content",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "0": {
                        "description": ""
                    }
                }
            }
        },
        "/user/upload/setUserImage": {
            "post": {
                "security": [
                    {
                        "x-token": []
                    }
                ],
                "description": "用户可上传图片",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "设置用户图片",
                "operationId": "set_user_image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "用户图片",
                        "name": "content",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "0": {
                        "description": ""
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.RandomUser": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer",
                    "example": 25
                },
                "coverImageUrl": {
                    "type": "string",
                    "example": "cover.png"
                },
                "lat": {
                    "type": "number",
                    "example": 22.51
                },
                "lng": {
                    "type": "number",
                    "example": 113.95
                },
                "location": {
                    "type": "string",
                    "example": "南山区"
                },
                "occupation": {
                    "type": "string",
                    "example": "平面设计师"
                },
                "petName": {
                    "type": "string",
                    "example": "Amy"
                },
                "userName": {
                    "type": "string",
                    "example": "豆豆"
                }
            }
        },
        "controllers.RecommendedUser": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer",
                    "example": 25
                },
                "coverImageUrl": {
                    "type": "string",
                    "example": "cover.png"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "img1.jpg",
                        "img2.jpg"
                    ]
                },
                "lat": {
                    "type": "number",
                    "example": 22.51
                },
                "lng": {
                    "type": "number",
                    "example": 113.95
                },
                "location": {
                    "type": "string",
                    "example": "南山区"
                },
                "occupation": {
                    "type": "string",
                    "example": "平面设计师"
                },
                "petName": {
                    "type": "string",
                    "example": "Amy"
                },
                "tags": {
                    "type": "string",
                    "example": "猫控 读书达人 电影爱好者"
                },
                "userName": {
                    "type": "string",
                    "example": "豆豆"
                },
                "verified": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "controllers.UserDetails": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer",
                    "example": 25
                },
                "birthday": {
                    "type": "string",
                    "example": "1988-10-2"
                },
                "constellation": {
                    "type": "string",
                    "example": "处女座"
                },
                "cover_Image": {
                    "type": "string",
                    "example": "cover.png"
                },
                "declaration": {
                    "type": "string",
                    "example": "交友宣言"
                },
                "education": {
                    "type": "string",
                    "example": "本科"
                },
                "gender": {
                    "type": "integer",
                    "example": 1
                },
                "height": {
                    "type": "string",
                    "example": "165cm"
                },
                "hobbies": {
                    "type": "string",
                    "example": "兴趣爱好"
                },
                "hometown": {
                    "type": "string",
                    "example": "湖南长沙"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "img1.jpg",
                        "img2.jpg"
                    ]
                },
                "income": {
                    "type": "string",
                    "example": "15-25w"
                },
                "location": {
                    "type": "string",
                    "example": "深圳"
                },
                "marriage": {
                    "type": "string",
                    "example": "未婚"
                },
                "occupation": {
                    "type": "string",
                    "example": "平面设计师"
                },
                "purpose": {
                    "type": "string",
                    "example": "交友"
                },
                "self_Desc": {
                    "type": "string",
                    "example": "自我描述"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "猫控",
                        "读书达人",
                        "电影爱好者",
                        "旅行者"
                    ]
                },
                "the_One": {
                    "type": "string",
                    "example": "希望另一半的样子"
                },
                "userName": {
                    "type": "string",
                    "example": "豆豆"
                },
                "weight": {
                    "type": "string",
                    "example": "43kg"
                }
            }
        },
        "controllers.UserDetailsUpdate": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer",
                    "example": 25
                },
                "birthday": {
                    "type": "string",
                    "example": "1988-10-2"
                },
                "constellation": {
                    "type": "string",
                    "example": "处女座"
                },
                "declaration": {
                    "type": "string",
                    "example": "交友宣言"
                },
                "education": {
                    "type": "string",
                    "example": "本科"
                },
                "gender": {
                    "type": "integer",
                    "example": 1
                },
                "height": {
                    "type": "string",
                    "example": "165cm"
                },
                "hobbies": {
                    "type": "string",
                    "example": "兴趣爱好"
                },
                "hometown": {
                    "type": "string",
                    "example": "湖南长沙"
                },
                "income": {
                    "type": "string",
                    "example": "15-25w"
                },
                "location": {
                    "type": "string",
                    "example": "深圳"
                },
                "marriage": {
                    "type": "string",
                    "example": "未婚"
                },
                "occupation": {
                    "type": "string",
                    "example": "平面设计师"
                },
                "purpose": {
                    "type": "string",
                    "example": "交友"
                },
                "self_Desc": {
                    "type": "string",
                    "example": "自我描述"
                },
                "tags": {
                    "type": "string",
                    "example": "猫控 读书达人 电影爱好者 旅行者"
                },
                "the_One": {
                    "type": "string",
                    "example": "希望另一半的样子"
                },
                "userName": {
                    "type": "string",
                    "example": "豆豆"
                },
                "weight": {
                    "type": "string",
                    "example": "43kg"
                }
            }
        },
        "models.AutoLogin": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "xtdad-fdfdsf"
                }
            }
        },
        "models.BasicInfo": {
            "type": "object",
            "properties": {
                "birth_day": {
                    "type": "string",
                    "example": "2010-10-09"
                },
                "constellation": {
                    "type": "string",
                    "example": "白羊座"
                },
                "education": {
                    "type": "string",
                    "example": "本科"
                },
                "gender": {
                    "type": "integer",
                    "example": 1
                },
                "height": {
                    "type": "number",
                    "example": 178
                },
                "hometown": {
                    "type": "string",
                    "example": "重庆"
                },
                "location": {
                    "type": "string",
                    "example": "深圳"
                },
                "marriage": {
                    "type": "string",
                    "example": "未婚"
                },
                "occupation": {
                    "type": "string",
                    "example": "设计师"
                },
                "weight": {
                    "type": "number",
                    "example": 56.5
                }
            }
        },
        "models.Fan": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer",
                    "example": 26
                },
                "coverImage": {
                    "type": "string",
                    "example": "https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTL13ic0iaA0ffWldrLjv9Ou02CuJCcjuKJ7rAzatVEzEUsrceUEdIuSiaR7bnicf5X2puMFRNDLrPEJlw/132"
                },
                "location": {
                    "type": "string",
                    "example": "广东，深圳"
                },
                "occupation": {
                    "type": "string",
                    "example": "产品经理"
                },
                "petName": {
                    "type": "string",
                    "example": "一个宠物"
                },
                "status": {
                    "type": "integer",
                    "example": 1
                },
                "uid": {
                    "type": "integer",
                    "example": 1
                },
                "username": {
                    "type": "string",
                    "example": "苹果香蕉"
                }
            }
        },
        "models.FocusRequest": {
            "type": "object",
            "properties": {
                "on": {
                    "type": "string",
                    "example": "2"
                },
                "status": {
                    "type": "string",
                    "example": "1"
                }
            }
        },
        "models.HomepageInfo": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string",
                    "example": "avatar1-1234.jpg"
                },
                "location": {
                    "type": "string",
                    "example": "广东,深圳"
                },
                "pet_food": {
                    "type": "integer",
                    "example": 320
                },
                "pet_name": {
                    "type": "string",
                    "example": "宠物猫猫"
                },
                "stat": {
                    "$ref": "#/definitions/models.RelationStat"
                },
                "user_name": {
                    "type": "string",
                    "example": "用户1"
                }
            }
        },
        "models.InfoCompletionLevel": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.Pagination": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer",
                    "example": 4
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "models.PetRequest": {
            "type": "object",
            "properties": {
                "birthday": {
                    "type": "string",
                    "example": "2021-10-12"
                },
                "description": {
                    "type": "string",
                    "example": "这是一个好宠物"
                },
                "pet_Name": {
                    "type": "string",
                    "example": "狗狗2022"
                },
                "sex": {
                    "type": "string",
                    "example": "MM"
                },
                "weight": {
                    "type": "number",
                    "example": 3.2
                }
            }
        },
        "models.PetResponse": {
            "type": "object",
            "properties": {
                "birthday": {
                    "type": "string",
                    "example": "2021-10-12"
                },
                "description": {
                    "type": "string",
                    "example": "这是一个好宠物"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "img1.jpg",
                        "img2.jpg"
                    ]
                },
                "pet_Name": {
                    "type": "string",
                    "example": "狗狗2022"
                },
                "sex": {
                    "type": "string",
                    "example": "MM"
                },
                "weight": {
                    "type": "number",
                    "example": 3.2
                }
            }
        },
        "models.RecommendSetting": {
            "type": "object",
            "properties": {
                "age_Max": {
                    "type": "integer",
                    "example": 40
                },
                "age_Min": {
                    "type": "integer",
                    "example": 22
                },
                "gender": {
                    "type": "string",
                    "example": "女生"
                },
                "hometown": {
                    "type": "string",
                    "example": "同省优先"
                },
                "location": {
                    "type": "string",
                    "example": "只要同城"
                },
                "pet_Lover": {
                    "type": "string",
                    "example": "喜欢就行"
                },
                "tags": {
                    "type": "string",
                    "example": "不限"
                }
            }
        },
        "models.RelationStat": {
            "type": "object",
            "properties": {
                "focus_by_new": {
                    "type": "integer",
                    "example": 4
                },
                "focus_on_total": {
                    "type": "integer",
                    "example": 24
                },
                "focused_by_total": {
                    "type": "integer",
                    "example": 50
                },
                "know_me_new": {
                    "type": "integer",
                    "example": 3
                },
                "know_me_total": {
                    "type": "integer",
                    "example": 20
                },
                "viewed_by_new": {
                    "type": "integer",
                    "example": 10
                },
                "viewed_by_total": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "models.SquareSettings": {
            "type": "object",
            "properties": {
                "gender": {
                    "type": "string",
                    "example": "女生"
                },
                "location": {
                    "type": "string",
                    "example": "不限"
                }
            }
        },
        "models.Token": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string",
                    "example": "cdaefj93sds-eqedsdsdsa-3sadasdsss"
                },
                "expiresIn": {
                    "type": "integer",
                    "example": 186624000
                },
                "tokenType": {
                    "type": "string",
                    "example": "bearer"
                }
            }
        },
        "models.UserGender": {
            "type": "object",
            "properties": {
                "gender": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.UserIMSig": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "sig": {
                    "type": "string"
                }
            }
        },
        "models.UserProfileForm": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "xtdad-fdfdsf"
                },
                "encryptedData": {
                    "type": "string",
                    "example": "7SfFtStsHqKZYhbIkke3BH2bCRzGD15T0jEiUtuksrl9lDeHm9LsPmswJymBXuinPCiXkZhd/uq7s7pACTvbWuvvoKEwz5fAJ6Vr9bTx79XVxiIN4r+Fwm6QHO9DjPkFrxTGAZvMYLyH6IOyOV/nmmlMoBM3G4peSnBi1qCYukwlyCMNp67lb93wSiPAoI7eRhYYw8ayPTsZ/MAJ9CBBUiCwM5aFOUWrMKNTikeq7YVjNCv7KCz0LJTrMKda0YMS0J/034L8x9vJ1OnIkxlWVMQEy/f55IfWVHI1I1fSKd5azzyVKXCbWDpU0PLJnU8XM/l4L7ZUlDOcRMR5KQVGhB9rIjVkykdXUPQK87v8lpnitslK06XceOJqDjK6mRkhJWOYpFUozZa6idFV6xmLZX8bkBsLxczzp1h/satEH7rIz3nKbxd3O1c+3dI2soSt8qFtaumcGdwhenTm+at0gxccAp8JD8PZiB5ZDLTofZIQ4RmI004SIExYUDZUje9mZO+3aC8McVwzrEyK7NKD/NZ5/dYPgDRwzBl1Vm99niY="
                },
                "iv": {
                    "type": "string",
                    "example": "z3tGYrgMcbLzd0qXqZuduQ=="
                },
                "rawData": {
                    "type": "string",
                    "example": ""
                },
                "signature": {
                    "type": "string",
                    "example": ""
                },
                "userInfo": {
                    "type": "string",
                    "example": ""
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "https://hellopeer.net",
	BasePath:         "/api/v0.1",
	Schemes:          []string{},
	Title:            "Hello Peer API",
	Description:      "Hello Peer是一款基于兴趣的社交应用。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
